### ISSUE TITLE
有sh为啥重写Go了。。。。

### ISSUE THREAD

**Issue by CoiaPrant** [sjlleo/netflix-verify#1]
提示 此方法不一定准确 建议使用官方重定向到的URL进行判断 完毕

**Comment by sjlleo** [comment]
之前写的练手项目，想着就传上来了，不知道谁发到梨园上来了233

**Comment by airline12138** [comment]
> 之前写的练手项目，想着就传上来了，不知道谁发到梨园上来了233

梨园那边是写的匿名投稿，而且用的是“发现”这个词，发布时间和上传时间相似，如果是本人的话还是建议正常投稿

**Comment by sjlleo** [comment]
> 
> 
> > 之前写的练手项目，想着就传上来了，不知道谁发到梨园上来了233
> 
> 梨园那边是写的匿名投稿，而且用的是“发现”这个词，发布时间和上传时间相似，如果是本人的话还是建议正常投稿

问题是真的不是我本人投的搞，如果硬是要说是我本人投的我也没办法了。
