### ISSUE TITLE
往NF的流量没有走特定的网际协议（IPv4/IPv6）导致无法解锁

### ISSUE THREAD

**Issue by 1klakla1** [sjlleo/netflix-verify#12]
美国和新加坡的机器都试了。

**Comment by jaywongs** [comment]
同，新加坡SG，显示支持ipv4的自制剧和非自制剧，ipv6显示不支持非自制剧，但实际只显示自制剧。

**Comment by 1klakla1** [comment]
> 同，新加坡SG，显示支持ipv4的自制剧和非自制剧，ipv6显示不支持非自制剧，但实际只显示自制剧。

我的问题解决了，你看看能不能参考下：
我的机器IPV4支持解锁非自制，IPV6不支持。
通过路由指定流量走IPV4以后可以实现全解锁了。

**Comment by jaywongs** [comment]
看来跟你一样的问题，应该是优先ipv6解析，路由指定流量我试试

**Comment by sjlleo** [comment]
经过查看，并未发现脚本判断有误，对于流量不走IPv4/IPv6的情况可使用`CoreDNS`自定义netflix.com的域名解析，屏蔽IPv4/IPv6的解析结果。

**Comment by 1klakla1** [comment]
> 经过查看，并未发现脚本判断有误，对于流量不走IPv4/IPv6的情况可使用`CoreDNS`自定义netflix.com的域名解析，屏蔽IPv4/IPv6的解析结果。

非常感谢！一次乌龙事件，抱歉！
