### ISSUE TITLE
无法正确测试vps的ipv4

### ISSUE THREAD

**Issue by jinwyp** [sjlleo/netflix-verify#15]
好几台机器 测试显示 

模式：详细信息模式
[IPv4测试]
NetFlix不为您测试的出口IP提供服务

但用其他脚本测试显示可以解锁
bash <(curl -sSL "https://raw.githubusercontent.com/xb0or/nftest/main/netflix.sh")

恭喜 你的IP可以打开Netflix 并解锁全部流媒体 区域: NFVDID=BQFMAAEBEHFUSNU78GFBAYVKKIYZYYHAVB2CZGCJ8RQNQHNGD7P8UJ20MMM3VP5RS3JDOTOMNFG9FXUPGHR4ZCBHNL3ZBSNVQYACEYS7KK73DDOP7NDATW%3D%3D;

if UnblockTest(areaAvailableID, ipv4) { 某些判断出了点问题

**Comment by sjlleo** [comment]
您是否使用了一些奇怪的办法来解锁Netflix？请告知我您的系统版本，谢谢。

**Comment by jinwyp** [comment]
> 您是否使用了一些奇怪的办法来解锁Netflix？请告知我您的系统版本，谢谢。

系统是centos 8 
不太清楚具体为什么ipv4 测试显示无法 NetFlix不为您测试的出口IP提供服务  


用的是 我自己的脚本安装了warp  解锁 通过v2ray 的路由设置解锁的
https://github.com/jinwyp/one_click_script#installation-linux-kernel-wireguard
就是warp提供了一个本机的127.0.0.1的一个sock5端口 然后v2ray路由设置规则解锁

希望脚本除了测试ipv4 ipv6 , 同时能增加一个走sock5端口代理 解锁的测试

具体情况我稍后再试试有哪些情况

**Comment by sjlleo** [comment]
程序会会使用该系统代理但需首先设置为系统代理，反之则不会使用这个socks代理。

它只会根据本身网络进行检测，如果需要让程序本身也可以检测到请将设置系统代理或者使用WireGuard VPN模式。
