### ISSUE TITLE
半解锁机器报名

### ISSUE THREAD

**Issue by asipirin1120** [sjlleo/netflix-verify#17]
现在手上有台机子，和最后描述的半解锁状态一致。即可以观看一部分的非自制剧，但在点入地域标签后，不显示任何内容。

然后更怪的来了。该IP隔段时间（约为几个小时或一日）可以恢复全解锁状态。也就在这种时候能好好收看地域限定和非自制剧。

希望能对研究有帮助。

**Comment by feition** [comment]
我的也是CF WARP IPV6只解锁了自制，非自制没有解锁，我也报一个名
