### ISSUE TITLE
我能提供一些半解锁的机器的信息给您

### ISSUE THREAD

**Issue by jlynnc** [sjlleo/netflix-verify#19]
通过对不同的设备和梯子进行测试，发现了如下规律：
环境说明：
1.梯子（都是使用新加坡线路）
梯子A: 使用dns解锁的方式访问新加坡奈飞，用不了几天就会挂（看不了自制剧，在奈飞的账号里可以看到流媒体地址变成了香港）
梯子B：使用直连ip的方式访问新加坡奈飞，这个没问题
2.设备
1. AppleTV4K
梯子A正常时，一切正常（可看非自制），梯子被封后就只能看自制了，即便切换上述梯子B后也无法恢复正常，和您对于半解锁的描述一模一样（尝试过重启恢复换账号等一系列操作），只有等几天后使用正常梯子才能恢复
2. PC
和梯子相关，梯子被封的话就无法看非自制了（自制剧一直没问题），但是切换到上述梯子B后就一切正常了
3. Sony TV
同上2
4. 手机&电脑
同上2
5. PS5&NS
同上2

我也知道您这边需要的是原生vps的机器，但是实在是全网都没人讨论关于半解锁的问题，这个appletv的表现让我很不爽，常常就是几天看不了，如需我提供什么信息请联系我，感谢！

**Comment by sjlleo** [comment]
您好，目前半解锁功能已经不在待办进程当中，感谢您的发帖
