### ISSUE TITLE
半解鎖shadowsocks

### ISSUE THREAD

**Issue by SyXuan** [sjlleo/netflix-verify#20]
兩天前正常，今天開始半解鎖，看不到地區推薦

Server: Shadowsocks

機器: iPhone(Shadowrocket), iPad(Shadowrocket), Android(影梭), Google TV(影梭), Mac(ShadowsocksX-NG)

環境皆為自架可提供測試

**Comment by sjlleo** [comment]
您好，目前半解锁功能已经不在待办进程当中，感谢您的发帖
