### ISSUE TITLE
生成的文件名能否不携带版本号

### ISSUE THREAD

**Issue by sduo** [sjlleo/netflix-verify#21]
Github 可以使用 latest 标签来快速定位到最新版本，但是一旦文件名中包含了版本号就需要手工修改地址了。
如：https://github.com/sjlleo/netflix-verify/releases/latest/download/nf_2.61_linux_amd64

**Comment by sjlleo** [comment]
感谢您的提议，我会在下一个版本取消版本号信息

**Comment by sjlleo** [comment]
格式目前暂定为 `nf_linux_amd64` `nf_windows_386.exe` 等

**Comment by sduo** [comment]
谢谢~
