### ISSUE TITLE
没有 win 直接运行的exe文件吗

### ISSUE THREAD

**Issue by fanqieD** [sjlleo/netflix-verify#25]
大佬，我装完了go语言，下载了压缩包，但是还是不会用，有没有小白一点的直接win可以用的

**Comment by sjlleo** [comment]
既然装好了 Golang 环境，打开 终端 `cd` 进入解压后的目录里（Win11也可以直接进入解压目录，右键选择”在终端中打开“），执行 `go run main.go`，生成可执行文件 `go build main.go`

**Comment by fanqieD** [comment]
会了会了  已经搞出来了  测试的话是用v2 还是clash？ 要全局吗？

**Comment by fanqieD** [comment]
> 既然装好了 Golang 环境，打开 终端 `cd` 进入解压后的目录里（Win11也可以直接进入解压目录，右键选择”在终端中打开“），执行 `go run main.go`，生成可执行文件 `go build main.go`

会了会了 已经搞出来了 测试的话是用v2 还是clash？ 要全局吗？

**Comment by fanqieD** [comment]
额 无论怎么测都是  Netflix在您的出口IP所在的国家不提供服务  即使我使用已知的已解锁的节点
