### ISSUE TITLE
OpenWRT 终端无法通过 wget 保存文件至本地

### ISSUE THREAD

**Issue by meroshyxoqo4** [sjlleo/netflix-verify#26]
* 运行环境 : x86 openwrt  Linux 5.4.199 x86_64
* 执行的操作 :  `./nf`
* 部分报错 : 
 ` Length: 4550656 (4.3M) [application/octet-stream] `
`Saving to:  'nf' `

`2022-08-02 02:09:58 (3.49 MB/s) - 'nf' saved [4550656/4550656]`
`bash: ./nf: No such file or directory`

**Comment by sjlleo** [comment]
`No such file or directory` 是找不到文件的意思，请先使用 `ls` 确认当前目录下是否已经正常下载该二进制文件，和软件无关。

**Comment by sjlleo** [comment]
此issue将被关闭，如有疑问再重新打开即可
