### ISSUE TITLE
程序识别可以观看，但实际无法登录

### ISSUE THREAD

**Issue by nfmd** [sjlleo/netflix-verify#27]
返回结果：
**NetFlix 解锁检测小工具 v3.0 By @sjlleo**
[IPv4]
您的出口IP完整解锁Netflix，支持非自制剧的观看
NF所识别的IP地域信息：法国

[IPv6]
您的网络可能没有正常配置IPv6，或者没有IPv6网络接入

ip：141.145.194.xx

登录时，提示密码错误，已确定账户没有问题

**Comment by sjlleo** [comment]
你好，

这概率是因为你的出口IP同时登录了多个账户导致的，考虑到账号的隐私性问题，这种情况 `netflix-verify` 没有办法判断。目前 `netflix-verify` 只能判断是否IP解锁，关于IP的风控问题没办法检测。

Thanks.

Best Regards,
Leo Shen

**Comment by nfmd** [comment]
该ip短期内未登录过netflix
在更换ip后，仍无法解决，可能是ip段风控导致
我会继续排查此问题
