### ISSUE TITLE
不支持奈飞，但能不能也加入下IP地区信息显示

### ISSUE THREAD

**Issue by rkygogo** [sjlleo/netflix-verify#31]
[IPv4]
Netflix在您的出口IP所在的国家不提供服务
++++++++++IP地区信息
[IPv6]
Netflix在您的出口IP所在的国家不提供服务
++++++++++IP地区信息

虽不支持奈飞，但能不能也加入下IP地区信息显示？？

**Comment by yangshuochina** [comment]
没必要吧，都不支持非自制了，还在乎哪个地区吗？再说了，你自己的节点，能不知道哪个地区？

**Comment by sjlleo** [comment]
看起来是是访问没有走到节点上，不支持Netflix的意思是连自制剧都看不了，连登录、注册都不行，这个一般都是检测为国区才会出来的。

试着用 `-proxy` 设置一下代理地址吧，比如 `-proxy socks5://127.0.0.1:1080`

**Comment by sjlleo** [comment]
> > 看起来是是访问没有走到节点上，不支持Netflix的意思是连自制剧都看不了，连登录、注册都不行，这个一般都是检测为国区才会出来的。
> > 
> > 试着用 `-proxy` 设置一下代理地址吧，比如 `-proxy socks5://127.0.0.1:1080`
> 
> 你的意思是脚本其实是支持这种不支持奈飞的地区显示地区名称？，比如中国？

只有netflix不提供服务的地方不会显示地区名，比如古巴。
