### ISSUE TITLE
Is possible to support linux-s390x?

### ISSUE THREAD

**Issue by biozzl** [sjlleo/netflix-verify#32]
Is possible to support linux-s390x?

**Comment by sjlleo** [comment]
Hi biozzl,

`linux-s390x` is easy to support for go and now it is available.

Check this tag: https://github.com/sjlleo/netflix-verify/releases/tag/v3.1.0-1

**Comment by biozzl** [comment]
> Hi biozzl,
> 
> `linux-s390x` is easy to support for go and now it is available.
> 
> Check this tag: https://github.com/sjlleo/netflix-verify/releases/tag/v3.1.0-1

Thank you so much!
