### ISSUE TITLE
无法准确判断

### ISSUE THREAD

**Issue by zhangjunjie6b** [sjlleo/netflix-verify#34]
研究了下原理应该访问3个片源通过返回header判断权限，
```
	AreaAvailableID        = 80018499
	SelfMadeAvailableID    = 80197526
	NonSelfMadeAvailableID = 70143836
```
我刚用NF不久遇见一个问题，在我单独访问
https://www.netflix.com/title/81370751 是正常的，但是登陆上账号就没权限了。

不知道有没有更准确的检查手段

**Comment by sjlleo** [comment]
#27 重复的 issue
