### ISSUE TITLE
Como

### ISSUE THREAD

**Issue by Tyson39** [sjlleo/netflix-verify#36]
https://www.netflix.com/es/login?nextpage=https%3A%2F%2Fwww.netflix.com%2FpartnerLinkedProfile

**Comment by sjlleo** [comment]
Thank you for commenting on my 'netflix-verify'. 

However, I am not sure I understand the purpose of the link you posted, as it seems to be a Netflix login page and not related to my script. Can you please provide more context or explain the relevance of this link to my script? 

Thank you.
