### ISSUE TITLE
V2.51解锁判断不准

### ISSUE THREAD

**Issue by ymcoming** [sjlleo/netflix-verify#4]
实测老版本是准确的，IPV6解锁了非自制剧。

-----------------------------------------------------------------------------
** NetFlix 解锁检测小工具 v2.5 By @sjlleo **
[IPV4测试]
NetFlix在您测试的出口IP所在的地区提供服务，宽松版权的自制剧可以解锁
->> 正在检查是否完整支持自制剧 <<-
支持解锁全部的自制剧
->> 正在检查支持的NetFlix地区 <<-
不支持解锁非自制剧

[IPV6测试]
NetFlix在您测试的出口IP所在的地区提供服务，宽松版权的自制剧可以解锁
->> 正在检查是否完整支持自制剧 <<-
支持解锁全部的自制剧
->> 正在检查支持的NetFlix地区 <<-
支持解锁非自制剧
原生IP地域解锁信息：香港区 NetFlix

-----------------------------------------------------------------------------

而V2.51则显示：
** NetFlix 解锁检测小工具 v2.51 By @sjlleo **
模式：简洁信息模式
[IPV4测试]
您的出口IP不能解锁Netflix，仅支持自制剧的观看

[IPV6测试]
您的出口IP不能解锁Netflix，仅支持自制剧的观看

-----------------------------------------------------------------------------

**Comment by sjlleo** [comment]
已经锁定问题，等会儿更新。

**Comment by sjlleo** [comment]
已经更新，麻烦再测试一下，谢谢。

**Comment by ymcoming** [comment]
已解决，谢谢！


** NetFlix 解锁检测小工具 v2.51 By @sjlleo **
模式：详细信息模式
[IPV4测试]
NetFlix在您测试的出口IP所在的地区提供服务，宽松版权的自制剧可以解锁
->> 正在检查是否完整支持自制剧 <<-
支持解锁全部的自制剧
->> 正在检查支持的NetFlix地区 <<-
不支持解锁非自制剧

判断结果：不支持Netflix解锁
NF库识别的IP地域信息：韩国区(KR) NetFlix 非原生IP

[IPV6测试]
NetFlix在您测试的出口IP所在的地区提供服务，宽松版权的自制剧可以解锁
->> 正在检查是否完整支持自制剧 <<-
支持解锁全部的自制剧
->> 正在检查支持的NetFlix地区 <<-
支持解锁非自制剧

判断结果：完整支持Netflix解锁
原生IP地域解锁信息：香港区(HK) NetFlix 原生IP
