### ISSUE TITLE
提供3合1检测脚本(Netflix + YoutubeCheck + DisneyPlus) 

### ISSUE THREAD

**Issue by samleong123** [sjlleo/netflix-verify#6]
您好，我想问下作者能不能提供3合1检测脚本，Netflix + YoutubeCheck + DisneyPlus 和 IPV4 + IPV6 
我提供了类似一个这样的脚本，均采用作者的项目
![image](https://user-images.githubusercontent.com/58818070/115526768-f4d6b900-a2c2-11eb-9227-1fd3657712e4.png)
因为有时候很懒惰一个一个复制指令 😂

[
[Netflix-Youtube-DisneyPlus-Check-Availability.zip](https://github.com/sjlleo/netflix-verify/files/6349529/Netflix-Youtube-DisneyPlus-Check-Availability.zip)
](url)

**Comment by sjlleo** [comment]
Hello,

很感谢您的提议！其实很早之前有做三合一脚本的打算，但是因为之前大学里学业繁忙一直未能如愿。
我会认真考虑在接下来空闲时间编此合集，后续依旧会加入Mac M1的arm64支持哦（我现在就是M1）。

Thank you very much.

**Comment by samleong123** [comment]
要不是您的DisneyPlus 脚本我都不知道我所在的国家DisneyPlus就要开通了 😂
