### ISSUE TITLE
适配ARM平台

### ISSUE THREAD

**Issue by samleong123** [sjlleo/netflix-verify#7]
系统: Ubuntu 20.04
CPU : Ampere Altra 80C ARM
(甲骨文 VM.Standard.A1.Flex)
运行会出现 : 
``` line 1: ./nf: cannot execute binary file: Exec format error ```

**Comment by sjlleo** [comment]
您好，

因为主机届ARM平台使用场景较少，所以未在ReadMe文档中写明，其实已经是编译且适配了的（只在Release中有列出）。

请您用以下命令行执行即可：
```shell
wget -O nf https://github.com/sjlleo/netflix-verify/releases/download/2.6/nf_2.6_linux_arm64 && chmod +x nf && clear && ./nf
```

感谢您发布Issue为本项目指出不足之处。

**Comment by sjlleo** [comment]
如果没有其他问题，我将关闭此Issue。
