### ISSUE TITLE
可不可以推荐几个解锁奈Netflix的服务商

### ISSUE THREAD

**Issue by vichen2021** [sjlleo/netflix-verify#8]
可不可以推荐几个解锁奈Netflix的服务商

**Comment by sjlleo** [comment]
你是说解锁NETFLIX的VPS服务商吗？这和本项目本身没有什么关系，Issue是用于解决这个项目问题、提出对该项目自己新想法的地方，还是建议不要发布一些与这些都不相关的内容，感谢你的理解。
