### ISSUE TITLE
2.6版本macOS11.2.3运行出错

### ISSUE THREAD

**Issue by goodryb** [sjlleo/netflix-verify#9]
$./nf_2.6_darwin_amd64

报错信息如下：

	0x11687a0
	0x1168960
	0x1168a00
	0x1168ae0
	0x1168c20
	0x1168ca0
	0x1168dc0
	0x1169180
	0x11692c0
	0x11694c0
	0x11695e0
	0x1169600
	0x11699c0
	0x1169a40
	0x1169c80
	0x1169fc0
	0x116a5a0
	0x116a760
	0x116a800
fatal error: invalid runtime symbol table
runtime: panic before malloc heap initialized

runtime stack:

**Comment by sjlleo** [comment]
你是M1芯片吧？

**Comment by goodryb** [comment]
> 你是M1芯片吧？

不是，Intel 的

![image](https://user-images.githubusercontent.com/3907975/120148798-5a4f8b00-c21b-11eb-8bd9-a786ee27c5d1.png)

**Comment by missuo** [comment]
你好。造成这样的问题的原因是：macOS的Terminal不会走你软件的Proxy，除非你使用ClashXPro开启增强模式、使用软路由或者使用Surge的增强模式。否则你的Terminal始终无法科学上网。这会导致与Netflix服务器无法通信，会报上面的错误。

**Comment by missuo** [comment]
简单介绍一下增强模式。增强模式是通过虚拟网卡的形式，使得Terminal以及Xcode这类软件强行走系统代理。

**Comment by goodryb** [comment]
@missuo  感谢解答，我理解你所说的是因为网络问题导致工具运行异常。 不过这个报错信息缺失难以理解。

**Comment by sjlleo** [comment]
怀疑是Linux直接编译的`darwin_amd64`二进制可执行文件过度精简，缺少必要依赖不能直接用于macOS `Big Sur`，需要从Google拉取依赖但是源被墙无法正常下载导致的。现在已经重新打包，请你再试一下还会不会出现这个问题。

因为我自己现在手里没有mac Intel的机器，这里特别感谢`missuo`提供的在Big Sur重新打包的可执行文件。

**Comment by zihaox** [comment]
> 你是M1芯片吧？

您好，我是M1芯片，12.0.1Monterey，报错exec format error: ./nf_2.61_linux_arm64，怎么办呢

**Comment by dlagez** [comment]
> > 你是M1芯片吧？
> 
> 您好，我是M1芯片，12.0.1Monterey，报错exec format error: ./nf_2.61_linux_arm64，怎么办呢

我也是报这个错误

**Comment by sjlleo** [comment]
用2.6版本的darwin_arm64版本，最新版没有编译darwin_arm64。
